### ISSUE TITLE
Graphite tags support

### ISSUE THREAD

**Issue by msaf1980** [bookingcom/carbonapi#111]
Hello.

Do You have any plans for graphite tags support ?

**Comment by grzkv** [comment]
Hi @msaf1980 ! We are considering this as one of the features to work on. Would you be interested in that?

**Comment by msaf1980** [comment]
Hi. I think. on next week I can start with it.

**Comment by grzkv** [comment]
Looking forward to your contributions! Please, ask if you have any questions.

**Comment by dorroddorrod** [comment]
Any updates regards tags support ?

**Comment by grzkv** [comment]
Tags support isn't planned in the foreseeable future.
