### ISSUE TITLE
Improve HTTP muxer

### ISSUE THREAD

**Issue by grzkv** [bookingcom/carbonapi#119]
There are several problems with current HTTP router (muxer):

- [x] some requests are served only when ending with a `/`, e.g. in `zipper` */metrics/find* does not work while */metrics/find/* does
- [x] routes have to be duplicated to accommodate for the previous point
- [ ] router and app code could be divided into separate files in `zipper`
- [x] a `302` is returned when incorrect endpoint is hit instead of `404`

We should also consider moving to [gorilla/mux](https://github.com/gorilla/mux) muxer.

- [x] Move to gorilla/mux
- [x] Routing tests also need to be added.

**Comment by anjali-sharma** [comment]
@grzkv Before writing the tests for routes, I'd like to refactor some coupled code across `app.go`, `http_handlers.go` and `routes.go` files. Possibly, split them further into packages with their own tests.

**Comment by grzkv** [comment]
@anjali-sharma Sounds like a nice idea.
