### ISSUE TITLE
Migrate to go modules

### ISSUE THREAD

**Issue by grzkv** [bookingcom/carbonapi#131]
Currently we use `dep` for dependency management. As it becomes deprecated in favor of `go modules`, we need to migrate as well.

**Comment by dgryski** [comment]
Given the current state of the modules tooling and ecosystem adoption, it's not clear if this is actually a "good first issue"

**Comment by grzkv** [comment]
We are kind of short on "good first issue"s, that's why. Majority require a lot of context.
