### ISSUE TITLE
Discuss: Making carbonapi compatible with M3 and replacing M3's graphite implementation

### ISSUE THREAD

**Issue by robskillington** [bookingcom/carbonapi#147]
Hey @grzkv thanks for attending the first M3 community meeting, it's taken me a little while but I'd love to start discussing how we could potentially leverage `carbonapi` in M3 both to make it compatible with M3 and to remove our dependency on our own internal graphite implementation which is not as complete as `carbonapi`.

The only thing we would need to verify is performance is somewhat similar.

How do you think we best proceed, perhaps I can draft a design document of the type of interfaces that would be required for us to start leveraging `carbonapi` and then seeing if we can move forward?

I think we'd want to be able to use `carbonapi` in process in M3's query service to apply query functions given a set of data, ideally it wouldn't be giving `carbonapi` fully decompressed datapoints to operate on but we're open to that if we can pool the underlying datapoint slices (to reuse between queries, etc).

**Comment by grzkv** [comment]
Hey @robskillington ! Thanks for reaching out. Let's plan a call and have a broader discussion. How does that sound?

**Comment by robskillington** [comment]
@grzkv great yes let's do that, you can find a time on my calendar here:
https://chronosphere.appointlet.com/s/rob-skillington-30-minutes
