### ISSUE TITLE
Failed to load header block rules

### ISSUE THREAD

**Issue by vedaprasad-j** [bookingcom/carbonapi#153]
Seeing too many "failed to load header block rules" in carbonapi logs. carbonapi talks to carbonzipper and carbonzipper is talking to go-carbon.

{
    "level": "DEBUG",
    "timestamp": "2019-06-02T15:52:27.757Z",
    "logger": "carbonapi",
    "message": "failed to load header block rules",
    "error": "open : no such file or directory"
}

**Comment by azhiltsov** [comment]
this is related to config parameter
blockHeaderFile:
please check what value you have specified there and check that carbonapi can write to the directory/file specified there

**Comment by vedaprasad-j** [comment]
@azhiltsov , i am not blocking any request based on headers. created any empty file for now.
