### ISSUE TITLE
Metric corruption in carbonzipper

### ISSUE THREAD

**Issue by vedaprasad-j** [bookingcom/carbonapi#158]
Setup : grafana -> carbon-api -> carbonzipper -> go-carbon.

All of the components are deployed as docker containers in AWS. i am seeing the below errors in carbonzipper.

{
    "level": "WARN",
    "timestamp": "2019-06-04T07:20:59.572Z",
    "logger": "zipper",
    "message": "metric corruption",
    "metric": "apps.fxxxxxxxxxxxxxx.channel_count",
    "corruption": 0.011111111111111112,
    "threshold": 0
}
i am seeing these errors only for a particular metric. My grafana UI hangs whenever i open the dashboard which uses the above metrics, so just wanted to know if it is because of the above error.

Any help is truly appreciated.

Thanks,
Ved

**Comment by gksinghjsr** [comment]
@vedaprasad-j what happens when you query the graphite backend itself with that particular metric. Can you post the result of the same?

**Comment by vedaprasad-j** [comment]
Hi gksinghjsr.

When i run the query from carbon-api i get this

root@adf7e03c37b7:/go/src/github.com/bookingcom/carbonapi# curl http://localhost:8081/metrics/find/?query=apps.freeswitch.production.australia.msdeb.debian-ms-a1.channel_count.channel_count
[{"allowChildren":0,"context":{},"expandable":0,"id":"apps.freeswitch.production.australia.msdeb.debian-ms-a1.channel_count.channel_count","leaf":1,"text":"channel_count"}]

**Comment by grzkv** [comment]
@vedaprasad-j Your corruption is `0.01`. This means, 1% of the points were missing on one of the backends. Your threshold for the warning is set to `0`, that's why you get it even in this case.

Normally, this is not too bad. You could check the backends if all the points are present.
