### ISSUE TITLE
"logger":"slow","message":"Slow Request"

### ISSUE THREAD

**Issue by vedaprasad-j** [bookingcom/carbonapi#164]
I am revamping our legacy graphite cluster.
The flow is grafana->carbonapi->carbonzipper->go-carbon (carbonserver)

One of your grafana dashboard has around ~150 panels and it takes for ever to load.upon investing all the stacks i see these messages in carbonapi

Jun 11 10:27:23 ip-10-202-43-35 carbonapi[27671]: {"level":"WARN","timestamp":"2019-06-11T10:27:23.412Z","logger":"slow","message":"Slow Request","time":2.000686764,"url":"/render","referer":""}

Jun 11 10:27:23 ip-10-202-43-35 carbonapi[27671]: {"level":"WARN","timestamp":"2019-06-11T10:27:23.412Z","logger":"slow","message":"Slow Request","time":2.000686764,"url":"/render","referer":""}

Is there something configured wrong on my end?
Any help would be highly appreciated.

Thanks in advance,
Ved.

**Comment by grzkv** [comment]
Hi,

It just means your requests take a bit longer to complete. As I can see from your log, they take around 2 seconds. It doesn’t mean anything is inherently wrong. Most likely everything is ok.

If your requests take long time to complete, the most likely reason is that they query many metrics.

**Comment by azhiltsov** [comment]
@grzkv I see at least two problems here:
- do we really want to preserve this log line? It confusing and not really helpful.
- If we really want to preserve it than it need to have carbonapi_uuid to become usefull
My guess that this request was already logged with INFO level, including "runtime" and all the rest.

**Comment by grzkv** [comment]
I think we should remove it. The durations histogram already has this info.
