### ISSUE TITLE
404 returned if no data points

### ISSUE THREAD

**Issue by msaf1980** [bookingcom/carbonapi#178]
In master branch now carbonapi return 404 code if no data points. It's not a good choose for all purposes (may be periodical logged metrics and we see error in grafana dashboard).
What's the reason for changed this ?

**Comment by grzkv** [comment]
This was added to make the system more transparent and problems more visible. With error codes returned, people report on problems and fix them faster.

**Comment by azhiltsov** [comment]
The main reason for this change is to make visible that data you query does not exist.
It should not return 404 if all data-points are null.
It should return 404 if metric does not exist.

**Comment by fgleason** [comment]
This case is not an error for me. When bringing up a new site I add it to the dashboards before the data exists so the night it starts taking traffic the dashboards are already setup.

**Comment by msaf1980** [comment]
Problems on storage backends ?
Some backends do not process database errors correctly. May be better handle database and network errors better ? 
I do some work on graphite-clickhouse (https://github.com/lomik/graphite-clickhouse/pull/46) and test some changes in carbonapi error handling (for example read error description from storage backend for display more informative error in grafana dashboard).

I make a PR (https://github.com/bookingcom/carbonapi/pull/179) with modified error handling.

**Comment by msaf1980** [comment]
> The main reason for this change is to make visible that data you query does not exist.
> It should not return 404 if all data-points are null.
> It should return 404 if metric does not exist.

Some storage backends (graphite-clickhouse) return empty response for this.
So it's not always correct.

**Comment by grzkv** [comment]
> Problems on storage backends?
>Some backends do not process database errors correctly. May be better handle database and network errors?

@msaf1980 Could you please elaborate these questions in a little bit more detail? I am not sure I understand the argument. Thanks.

 > Some storage backends (graphite-clickhouse) return empty response for this.

This seems like rather strange behaviour. If a metric does not exist, it would make sense not to return it. Maybe it'd make sense to change the behaviour of `graphite-clickhouse` instead?
