### ISSUE TITLE
Move from gometalinter to golandci-lint

### ISSUE THREAD

**Issue by jwkohnen** [bookingcom/carbonapi#189]
Gometalinter has been deprecated since 2019-04-07, the community consensus is to use golangci-lint now.

**Comment by jwkohnen** [comment]
fun fact: I wrote this is issue while waiting for gometalinter to terminate. I am 2 minutes in...

**Comment by grzkv** [comment]
Would you like to pick this one up?

**Comment by jwkohnen** [comment]
Sure.
