### ISSUE TITLE
Use viper for configuration management

### ISSUE THREAD

**Issue by anjali-sharma** [bookingcom/carbonapi#209]
Using https://github.com/spf13/viper for configuration management will mainly improve the following for the current config setup:

- Mechanism to find, load and unmarshal configuration (update in config format from eg. YAML to JSON would require minimal change.)
- Mechanism to set default options for different configuration options
- Setting up override values for flags
- live watching and re-reading of config files (if needed)

**Comment by anjali-sharma** [comment]
If it looks good to go, I'd like to pick this up.

**Comment by azhiltsov** [comment]
I am not sure that changing a config format is desired now. 
What features are currently missing:
- live watching and reload
- Config syntax validation
- Config logic validation (all parameters are recognized by the code)
- Config generation with sane defaults out of the code (extra invocation flag which will dump default config to a disk)
- Configuration from env variables for docker/k8s/containers (was there 78bf3815d06b71373f99749c4306324d0280db3d) but removed

**Comment by anjali-sharma** [comment]
@azhiltsov  Most of the above features you mentioned can be added via viper. It surely can be prioritized as needed. It's primarily intended as a suggestion.

**Comment by gunnihinn** [comment]
> Configuration from env variables for docker/k8s/containers (was there 78bf381) but removed

FWIW, Docker can mount the standard configuration files into a container. Kubernetes can do the same thing, or create a file inside a pod with whatever contents you want. It's not necessary to be able to configure things from environment variables to be able to run software there (can you imagine configuring nginx from environment variables to run it in k8s or docker containers?).

**Comment by grzkv** [comment]
Viper is nice, but I'd say it will not give a lot of value but will cost some effort.

**Comment by azhiltsov** [comment]
Taking in account what @gunnihinn said, I think we could live without configuration from ENV.
