### ISSUE TITLE
Do not forward bad queries to go-carbon?

### ISSUE THREAD

**Issue by bom-d-van** [bookingcom/carbonapi#215]
There is a case where carbonapi sending a bad query with something like 'xxx.yyy-[1', which happen to be causing go-carbon with trie to crash.

https://github.com/lomik/go-carbon/pull/303/commits/2ea3044d1950b8d7e191c5589b8be608217e7fe5

**Comment by azhiltsov** [comment]
We currently accept only [0-9a-zA-Z-_:#] via carbon-c-relay,
I believe it make sense to introduce a validator as configurable parameter in the carbonapi to filter improper characters and don't let them through

**Comment by grzkv** [comment]
We need to work-out a more specific policy for this. Then we can consider making the change. I'll close this as we won't do the change to only address this single specific instance. We can use this issue for reference later on.
