### ISSUE TITLE
applyByNode incorrectly counts fields

### ISSUE THREAD

**Issue by gringus** [bookingcom/carbonapi#249]
According to Graphite documentation [applyByNode](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.applyByNode) function should count fields (nodeNum option) starting from 0, but carbonAPI counts them starting from 1. In other words it means that:
```
 applyByNode(stats.counts.haproxy.*.*XX, 3, "asPercent(%.5XX, sumSeries(%.*XX))", "%.pct_5XX")
```
in Graphite would require
```
applyByNode(stats.counts.haproxy.*.*XX, 4, "asPercent(%.5XX, sumSeries(%.*XX))", "%.pct_5XX")
```
in CarbonAPI. Please make this consistent with Graphite.

**Comment by grzkv** [comment]
@justpresident would you consider picking this up since this is replated to #222
