### ISSUE TITLE
carbonapi: Internal Server Error (panicking) while calculating asPercent function on metrics with different resolutions

### ISSUE THREAD

**Issue by nloginov** [bookingcom/carbonapi#264]
**Suppose we have:**
* Metric `metric.hourly.value` with one hour resolution
* Metric `metric.two_hourly.value` with 2 hour resolution

**Then:**
* Calculating `asPercent(metric.hourly.value, metric.two_hourly.value)` leads to a panic error: `all targets failed with mixed errrors; merged errs: (expression eval failed: panic duting expr eval: runtime error: index out of range [3] with length 3, )`
* Calculating `asPercent(metric.hourly.value, keepLastValue(metric.two_hourly.value))` doesn't help, it's still panic

**Expected behaviour**
To be ok with that calculation as vanilla graphite does:

Steps to reproduce in vanilla graphite:

1. install graphite locally:
```
docker run -d \
 --name graphite \
 --restart=always \
 -p 80:80 \
 -p 2003-2004:2003-2004 \
 -p 2023-2024:2023-2024 \
 -p 8125:8125/udp \
 -p 8126:8126 \
 graphiteapp/graphite-statsd
```
2. Log in to change carbon settings
```

docker exec -it CONTAINER_ID /bin/sh
vi /opt/graphite/conf/storage-schemas.conf


Add the following content to the file after [carbon] section:

[hourly]
pattern = .*\.hourly\..*
retentions = 1h:90d

[two_hourly]
pattern = .*\.two_hourly\..*
retentions = 2h:90d
```
3. Restart docker

`docker restart CONTAINER_ID`
4. Fill up the data
```

# for two_hourly metric (one point)
echo local.two_hourly.value 100 `gdate -d "06/06/2020 04:21:22" +"%s"` | nc localhost 2003

# for hourly metric (11 points, 1 per hour)
for h in `seq 0 10`; do echo local.hourly.value $h `gdate -d "06/07/2020 0$h:21:22" +"%s"` | nc localhost 2003  ; done
```
5. Calculate the query in graphite:
![image](https://user-images.githubusercontent.com/947131/87132633-73afb780-c296-11ea-8576-bd1f9488d24d.png)

Blue - hourly metric

Green - two hourly metric (one point)

Red - asPercent calculation ( I can get rid of keepLastFunction and graphite will still render it, but only around one point as expected)

**Comment by avereha** [comment]
This should be fixed by https://github.com/bookingcom/carbonapi/pull/296
