### ISSUE TITLE
Refactor sendGlobAsIs ?

### ISSUE THREAD

**Issue by azhiltsov** [bookingcom/carbonapi#33]
We have 3 parameters:
sendGlobsAsIs: true|false
alwaysSendGlobsAsIs: true|false
maxBatchSize: int

Their logic is convoluted 
**sendGlobsAsIs** in _true_ is working together with **maxBatchSize**
 carbonapi is sending a find request and depending on amount of metrics returned from stores acts differently:
 * if amount of metrics is lower than maxBatchSize it sends request as is with globs
 * if amount of metrics is higher it uses list of metrics returned from find and query them one by one

**sendGlobsAsIs** in _false_ is always sending find and ignoring **maxBatchSize**

**alwaysSendGlobsAsIs** I suppose is neglecting **sendGlobsAsIs** settings and always send a render request without 'find'

Proposing deprecate **sendGlobsAsIs** and **alwaysSendGlobsAsIs** in favor of
**resolveGlobs:** true|false in conjunction with **maxBatchSize**

resolveGlobs: false -> send render query as it is
resolveGlobs: true -> send find query and if:
  count of metrics < maxBatchSize - send as it is
  count of metrics > maxBatchSize - group them in batches of maxBatchSize and send them in batches

**Comment by grzkv** [comment]
@azhiltsov Here's how it works in code:

1. We get a `render` request in `carbonapi`
2. We *expand* the globs and get the number of metrics after expansion `numMetrics`
3. The following logic is applied:
```
if (alwaysSendGlobsAsIs)
	send non-expanded
else if (sendGlobsAsIs && (numMetrics < maxBatchSize))
	send non-expanded
else
	send expanded one-by-one
```

This is a very complex logic. We need to re-think it.

**Comment by grzkv** [comment]
> **alwaysSendGlobsAsIs** I suppose is neglecting **sendGlobsAsIs**

Your supposition is correct.

> ...and always send a render request without 'find'

Surprisingly, `find` is *always* sent. Which is inefficient.

**Comment by grzkv** [comment]
Can we go with just one option? Only `sendGlobsAsIs` that turns expansion and preliminary find requests on and off. This can also be used well in conjunction with *clickhouse*

**Comment by azhiltsov** [comment]
I would rather avoid reusing the same configuration parameter if we are about to change it logic.
Check my original proposal about **resolveGlobs:** true|false in conjunction with **maxBatchSize**

**Comment by grzkv** [comment]
@azhiltsov I agree. We have to change the name. But can we do with just on param, i.e. *only* `resolveGlobs`?
