### ISSUE TITLE
Unknown content type 'application/octet-stream'

### ISSUE THREAD

**Issue by msaf1980** [bookingcom/carbonapi#34]
On last commit get error "Unknown content type 'application/octet-stream'", when receive responce from backend.
From commit 25bf30e27fd2e387279cc6207acee215860d82a5 all work fine.
This is strange, becouse no changes in pkg/backend/net/net.go and only "application/x-protobuf" and "application/protobuf" allowed.
For qiuck fix I add  "application/octet-stream" to Render and Find function in pkg/backend/net/net.go

Stacktrace:

{"level":"ERROR","timestamp":"2019-01-16T15:06:30.313+0300","logger":"render","message":"find error","carbonapi_uuid":"714f6d17-1a35-4a14-8aaa-02d0d7468250","username":"devops","metric":"test","error":"All backend requests failed: 1 backends: Unknown content type 'application/octet-stream'",
"errorVerbose":"Unknown content type 'application/octet-stream'
github.com/bookingcom/carbonapi/pkg/backend/net.Backend.Find
     /go/src/github.com/bookingcom/carbonapi/pkg/backend/net/net.go:462
github.com/bookingcom/carbonapi/pkg/backend/net.(*Backend).Find
    <autogenerated>:1
github.com/bookingcom/carbonapi/pkg/backend.Finds.func1
    /go/src/github.com/bookingcom/carbonapi/pkg/backend/rpc.go:134
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:23611 backends\nAll backend requests failed"}

**Comment by gksinghjsr** [comment]
@msaf1980 I did not understand the commits where you say the issue is. Also, a sample query/config to reproduce this would help us debug the issue.

**Comment by msaf1980** [comment]
>listen: "localhost:8888"
listenInternal: "localhost:7888"
concurency: 20
cache:
   type: "memcache"
   size_mb: 0
   defaultTimeoutSec: 60
   memcachedServers:
       - "127.0.0.1:11211"
cpus: 0
tz: ""
sendGlobsAsIs: true
maxBatchSize: 100000

>functionsConfig:
    graphiteWeb: /etc/carbonapi/graphiteWeb.yaml
    aliasByPostgres: /etc/carbonapi/aliasByPostgres.yaml

>graphite:
    host: "graphite-test:2003"
    interval: "60s"
    prefix: "carbon.api"
    pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: ""

>upstreams:
    buckets: 10
    timeouts:
        global: "30s"
        afterStarted: "20s"
        connect: "500ms"
    concurrencyLimit: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    backends:
        - "http://localhost:8090"
    graphite09compat: false
    
>expireDelaySec: 60
logger:
    - logger: ""
      file: "/var/log/carbonapi/carbonapi.log"
      level: "warn"
      encoding: "json"


Backend (graphite-clickhouse) really set content type 'application/octet-stream'.
So I don't undestend how it work for our current version.

**Comment by gksinghjsr** [comment]
Can you also specify the commit where it was working and where it stopped working?

**Comment by deniszh** [comment]
I also can reproduce with current master and clickhouse stack.

**Comment by grzkv** [comment]
@msaf1980 @deniszh We were able to reproduce this. #86 fixes it.

I am able to run `/find` and `/render` requests with *clickhouse* successfully. Everything should work.

Thanks for reporting this!
