### ISSUE TITLE
Automate documentation of compatibility between graphite-web and carbonapi

### ISSUE THREAD

**Issue by grzkv** [bookingcom/carbonapi#62]
The functional compatibility between `carbonapi` and `graphite-web` is maintained as a separate document [COMPATIBILITY.md](https://github.com/bookingcom/carbonapi/blob/master/COMPATIBILITY.md)

This document can get out-of-sync very easily and is quite likely out of date now.

We need to implement the automatic generation of it by calling and comparing outputs of `/functions` endpoints.

**Comment by Civil** [comment]
For go-graphite/carbonapi I just wrote https://github.com/go-graphite/carbonapi/blob/master/cmd/functiondiff/main.go this small tool that do somethink that you might want to have.

However I wrote this code mostly for myself, so the content of mine COMPATIBILITY.md is hardcoded there.

**Comment by grzkv** [comment]
@Civil 	Thanks for pointing this out. I have seen the code. We will use it for docs generation in #65 

This issue is about API diff between `graphite-web` and `carbonapi`, so it's a bit different. Or am I getting something wrong?

**Comment by Civil** [comment]
In my understanding, the code I've attached is exactly about this issue - it accepts 2 parameters - URL for carbonapi and URL for graphite-web, calls /funcitons API and do the diff between them. Then I create 3 lists of fucntions:
1. Supported functions (short descriptions)
2. Functions *not* supported by carbonapi
3. Functions that's supported by carbonapi, but that have differences in parameters.

I do not generate the docs based on /functions yet, however I had some plans on making a simple html+js frontend for searching over /functions output (but I don't know JS well enough to implement it).

**Comment by Civil** [comment]
https://github.com/go-graphite/carbonapi/blob/master/COMPATIBILITY.md#partly-supported-functions - that's the main reason why I wrote this thing.
