### ISSUE TITLE
Add graceful SIGINT handling

### ISSUE THREAD

**Issue by grzkv** [bookingcom/carbonapi#67]
Currently, we don't properly gracefully handle the termination signals.

The graceful shutdown should include
- the flushes
- stop receiving new requests
- finish hanging requests

**Comment by ksurent** [comment]
I wanted to take a look at this but as I sat down to think what would need to be done, I realised that this is probably already solved.

- both carbonapi and carbonzipper use Facebook's gracehttp which does graceful termination upon SIGTERM
- SIGINT is not really something you get in production use
- when developing, you probably want SIGINT to kill the thing ASAP (most of the time, anyway)

**Comment by avereha** [comment]
This issue is probably related to https://github.com/bookingcom/carbonapi/pull/229. It was  also created before.

**Comment by grzkv** [comment]
This issue needs a re-evaluation. I think, @avereha is best equipped to do that now.

**Comment by avereha** [comment]
Going to close this issue.
Let's reopen with specific bug report and reproduction steps if we find that we still have this issue(did not notice it in production).

**Comment by grzkv** [comment]
Totally agree. @avereha Thanks for reviewing.
