### ISSUE TITLE
Check usage of graphiteWeb function, remove if unused

### ISSUE THREAD

**Issue by grzkv** [bookingcom/carbonapi#76]
Seems like `graphiteWeb` function that is [here](https://github.com/bookingcom/carbonapi/blob/9dbbaac9ba4d4723a1d6181cc4fab089bb147993/expr/functions/graphiteWeb/function.go) is not used. It is not clear if it was ever used.

Need to figure out if it is still needed and clean-up if not.

**Comment by azhiltsov** [comment]
There was an idea to fallback to graphiteWeb if carbonapi receive a function which it does not know
From the commit cb0f37ebd6477ebd88d08301e02b434aca9c8f10  
* Initial work on proxying unknown functions to graphiteWeb.

**Comment by grzkv** [comment]
@azhiltsov Thanks for the clarification. Was it ever used or finished? Do we know if it works?

**Comment by azhiltsov** [comment]
it was newer used in prod and I do not know was it finished or not.

**Comment by grzkv** [comment]
I suggest we remove it then. We cannot keep broken things in the repository. It also depends on obsolete limiter that has to be cleaned up.

**Comment by azhiltsov** [comment]
As we are targeting to fully replace python graphite stack with carbonapi there will be no need in fallback logic. At current state I am fine with your proposal to remove it.
