### ISSUE TITLE
Actualize config examples, remove unused, add missing options

### ISSUE THREAD

**Issue by azhiltsov** [bookingcom/carbonapi#80]
Rename https://github.com/bookingcom/carbonapi/tree/master/config/carbonzipper.conf to yaml

is this being used?
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/carbonapi.yaml#L14

why this in upstreams section?
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/carbonapi.yaml#L77

What is this? Some comments needed with explanation.
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/carbonapi.yaml#L130-L132

keepalive every 30s? really?
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/carbonzipper.conf#L34

What do we cache exactly?
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/carbonzipper.conf#L40

Dead:
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/carbonzipper.conf#L51

what is this?
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/graphiteWeb.yaml

Do we use it? Where is the config parameter for this file?
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/graphTemplates.yaml

**Comment by azhiltsov** [comment]
what is this?
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/graphiteWeb.yaml

**Comment by azhiltsov** [comment]
Do we use it? Where is the config parameter for this file?
https://github.com/bookingcom/carbonapi/blob/133e554781d1dfd46c1675479eef362dca99ac90/config/graphTemplates.yaml

**Comment by azhiltsov** [comment]
https://github.com/bookingcom/carbonapi/blob/e56cfc0ccdf78fb49d937fbbc072265f124a7910/config/carbonzipper.conf#L43
Explain what exactly kind of cache is that?

**Comment by grzkv** [comment]
Closing because of #434
